language: php

php: 
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

notifications:
  irc: "irc.freenode.net#mattfarina"

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v